#!/bin/bash

load inquirer

check() {
  if [ ! -f $SERVICE_CONFIG ]; then
     touch $SERVICE_CONFIG
  fi

  config::load_file $SERVICE_CONFIG

  if [ -z "$SERVICE_STATIC_DIR" ]; then
    inquirer::text "请输入 SERVICE_STATIC_DIR:" value
    echo "SERVICE_STATIC_DIR=$value" > $SERVICE_CONFIG
  fi

  #@TODO
  export SERVICE_STATIC_NAME=$SERVICE_STATIC_NAME
  export SERVICE_STATIC_DIR=$SERVICE_STATIC_DIR
}

check $@
