version: '3.7'

services:
  static:
    container_name: ${SERVICE_STATIC_NAME}
    restart: always
    build:
      context: ./image
    volumes:
      - ${SERVICE_STATIC_DIR}:/usr/share/www/html

networks:
  default:
    external: true
    name: compose-ingress
